### ISSUE TITLE
TestPyPi feiler

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-rdf-parser#162]
Checking dist/fdk_rdf_parser-2.1.11.dev1659621023-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         No content rendered from RST source.

**Comment by valosnah** [comment]
Ser andre prosjekter har description som normalt i både testpypi og pypi, så noe ser ut til å være feil konfigurert

**Comment by NilsOveTen** [comment]
> Ble denne fikset @NilsOveTen ?

Nei, jeg bare fjerna testpypi fra actions frem til vi fiksa dette.

**Comment by jeffreiffers** [comment]
@terjesyl @NilsOveTen Er denne fremdeles aktuelt etter vi har laget ny parser service?

**Comment by NilsOveTen** [comment]
vi kommer til å fortsatt bruke biblioteket i parser-service, så dette forsvinner ikke av den grunn.

Men når det er sagt, vi kan fint lukke dette som noe vi ikke kommer til å fikse, er egentlig ikke noe vi brukte.
Det er jo greit å kunne teste en publisert versjon av nåværende main før vi kjørte ut ny versjon. Men det skjedde jo aldri, vi kasta jo alltid bare alt til pypi og testa den versjonen, og publiserte ny versjon med fiks om nødvendig :shrug:

**Comment by KjerstiSteien** [comment]
@terjesyl @NilsOveTen skal jeg bare lukke denne?

**Comment by terjesyl** [comment]
@KjerstiSteien Jeg kjenner ikke til hvordan TestPyPi ble brukt og tenkt brukt. Men du kan sikkert bare lukke denne som en won't fix.
