### ISSUE TITLE
Endre tjeneste-parse til å støtte cpsv-ap-no 1.0

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-rdf-parser#165]
Behov: https://github.com/Informasjonsforvaltning/behov/issues/650

issues:
- [x] #166 
- [x] #167
- [x] #168 
- [x] #169 
- [x] #170 
- [x] #171 
- [x] #172 
- [x] #173 
- [x] #174 
- [x] #175 
- [x] #176 
- [x] #179  
- [x] #180 
- [x] #181

**Comment by terjesyl** [comment]
@NilsOveTen Lukke denne?

**Comment by terjesyl** [comment]
Alle issues fullført
