### ISSUE TITLE
oppdater parse av tjenester til å hente ut relaterte regelverk

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-rdf-parser#172]
fra predikat `cv:hasLegalResource`

- title fra `dct:title`
- seeAlso fra `rdfs:seeAlso`
- relation fra `dct:relation`
  - identifier og/eller uri?

**Comment by terjesyl** [comment]
Trengs også `rdfs:seeAlso` her for visning av Referanser-feltet?
