### ISSUE TITLE
Noen felter ignoreres i PublicService

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-rdf-parser#215]
# Bug
Når parsereren konverterer en delvis parset Service til PublicService mangler felter i `add_cpsvno_servic_values` slik at disse feltene filtreres vekk fra PublicService.

## Løsning:
Legg til manglende verdier i `PublicService.add_cpsvno_service_values`. Gjelder bl.a.
- `thematicAreaUris`
- `losThemes`
- `euDataThemes`

- [ ] Undersøk om flere felter mangler
- [ ] Evt. oppdater tester så de er korrekte.

**Comment by KjerstiSteien** [comment]
- [ ] test
