### ISSUE TITLE
parse av datasetterier

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-rdf-parser#219]
### Alle datasett
- [x] enum med "Dataset" og "DatasetSeries" ut fra rdf:type

### Datasett som inngår i serie
- [x] uri til serie
- ~Objekt som har~
  - ~uri~
  - ~tittel (dct:title)~
  - ~fdk-id til serien (dcterms:identifier på CatalogRecord, altså Dataset.id)~

### Datasettserier
~Legg til antall datasett som tilhører serien~
- [x] Liste av uri'er med korrekt rekkefølge

- [x] Legg inn sjekk for og håndter sirkulære grafer, logg feil.
- [x] Sjekk at antall datasett med `inSeries` samsvarer med antall URI-er i datasettseriens liste. Logg feil ved brutt lenking i listen.

**Comment by terjesyl** [comment]
Endringer i parseren trengs
